### ISSUE TITLE
Add Option to Change Notebook Location

### ISSUE THREAD

**Issue by WheatMcGrass** [k0range/ideaNote#15]
**Problem**
Notebooks are currently saved to **%appdata%\ideanote\notebooks** without any option to move them

**Solution**
Add an option to change the location notebooks are saved

**Comment by k0range** [comment]
That's a good idea! I will add it in the next version.

**Comment by k0range** [comment]
Added in 588ff4b809b02c8e239e536b2211bad2021373c8. I'm currently working on releasing this version.

**Comment by k0range** [comment]
Released in 1.13.0!
The Microsoft Store version is in Certification, but will be available soon.
